#!/bin/sh

# Exit immediately if a command exits with a non-zero exit status
# set -e

VERB="$1"
shift

AP_DIR=/usr/bin/ardupilot
PROGRAM=arduplane


# -A Switch : uartA
# AP_CONSOLE="/dev/ttyS1"
# The Host GCS address
AP_CONSOLE="udp:192.168.1.43:14550"
# -B Switch : uartB
AP_GPS="/dev/ttyS2"
# -C Switch : uartC
AP_TELEM1="/dev/ttyS5"
# -D Switch : uartD
#AP_TELEM2="/dev/ttyS5"
# -E Switch : uartE
#AP_UNAMED1="/dev/ttyS5"
# -F Switch : uartF
#AP_UNAMED2="/dev/ttyS5"
# -G Switch : uartG
#AP_UNAMED3="/dev/ttyS5"
# -H Switch : uartH
#AP_UNAMED4="/dev/ttyS5"

# -l Switch : Flight Logs directory
AP_LOG_DIR="/var/APM/logs"  
# -t Switch : Terrain data directory
AP_MAP_DIR="/var/APM/terrain"
# -M Switch : Modules directory
AP_MOD_DIR="/usr/lib/ardupilot"
# -s Switch : Parameters storage directory
AP_PAR_DIR="/var/APM"

# Modules needed by the program
loadlist="uio uio_pruss uio_pdrv_genirq inv_mpu6050 bmp280 ak8975"

# Function to load modules
function loadmodules {
  for module in ${loadlist}
    do
      lsmod | grep ${module} > /dev/null 2>&1
      if [[ $? -eq 1 ]]; then
        echo -n "Loading ${module} ... "
        modprobe ${module}
        sleep 0.2
        echo "OK"
      else
        echo "${module} Already loaded"
      fi
    done
}
# END loadmodules

#-----------------------------------------------------------------------------------
case "$VERB" in
  start)
    echo "Starting ${PROGRAM}..."
    # Load Modules
    loadmodules

    # Start program in background
    APPID=`pidof ${PROGRAM}`
    if [ s${APPID} = "s" ]; then
      ${AP_DIR}/${PROGRAM} -l ${AP_LOG_DIR} -A ${AP_CONSOLE} -B ${AP_GPS} -C ${AP_TELEM1} -s ${AP_PAR_DIR}&
    else
      echo "An instance of ${PROGRAM} is already running..."
    fi
    echo "OK"
    ;;

  stop)
    echo -n "Stopping ${PROGRAM}: "
    APPID=`pidof ${PROGRAM}`
    if [ "s${APPID}" = "s" ]; then
      echo
      echo "${PROGRAM} is not running!"
    else
      kill -9 $APPID
      echo "OK"
    fi
    ;;

  restart)
    $0 stop
    sleep 2
    $0 start
    ;;

  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
